services:
    directus:
        image: directus/directus:11.4.0
        container_name: beauty_awakening_backend
        restart: always
        ports:
            - 8055:8055
        volumes:
            - ./database:/database
            - ./uploads:/uploads
            - ./extensions:/extensions
        environment:
            SECRET: ${SECRET}
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/database/data.db"
            WEBSOCKETS_ENABLED: "true"
            HOST: "0.0.0.0"
            PORT: "8055"
            PUBLIC_URL: "http://localhost:8055"
            LOG_LEVEL: "info"
            LOG_STYLE: "pretty"
            MAX_PAYLOAD_SIZE: "1mb"
            ROOT_REDIRECT: "./admin"
            SERVE_APP: "true"
            GRAPHQL_INTROSPECTION: "true"
            MAX_BATCH_MUTATION: "Infinity"
            RATE_LIMITER_ENABLED: "false"
            RATE_LIMITER_STORE: "memory"
            RATE_LIMITER_POINTS: "25"
            RATE_LIMITER_DURATION: "1"
            CACHE_ENABLED: "false"
            CACHE_TTL: "5m"
            CACHE_NAMESPACE: "system-cache"
            CACHE_AUTO_PURGE: "false"
            CACHE_AUTO_PURGE_IGNORE_LIST: "directus_activity,directus_presets"
            CACHE_STORE: "memory"
            ASSETS_CACHE_TTL: "30d"
            STORAGE_LOCATIONS: "local"
            STORAGE_LOCAL_DRIVER: "local"
            STORAGE_LOCAL_ROOT: "/uploads"
            ACCESS_TOKEN_TTL: "15m"
            REFRESH_TOKEN_TTL: "7d"
            REFRESH_TOKEN_COOKIE_SECURE: "false"
            REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"
            REFRESH_TOKEN_COOKIE_NAME: "directus_refresh_token"
            SESSION_COOKIE_TTL: "1d"
            SESSION_COOKIE_SECURE: "false"
            SESSION_COOKIE_SAME_SITE: "lax"
            SESSION_COOKIE_NAME: "directus_session_token"
            CORS_ENABLED: "true"
            CORS_ORIGIN: "true"
            CORS_METHODS: "GET,POST,PATCH,DELETE"
            CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
            CORS_EXPOSED_HEADERS: "Content-Range"
            CORS_CREDENTIALS: "true"
            CORS_MAX_AGE: "18000"
            EXTENSIONS_PATH: "./extensions"
            EXTENSIONS_AUTO_RELOAD: "false"
            EMAIL_FROM: ${EMAIL_SMTP_USER}
            EMAIL_TRANSPORT: "smtp"
            EMAIL_SENDMAIL_NEW_LINE: "unix"
            EMAIL_SENDMAIL_PATH: "/usr/sbin/sendmail"
            EMAIL_SMTP_HOST: "mail.stackmail.com"
            EMAIL_SMTP_PORT: "465"
            EMAIL_SMTP_SECURE: "true"
            EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
            EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
