services:
    directus:
        image: directus/directus:11.3.2
        container_name: beauty_awakening_backend
        restart: always
        ports:
            - 8055:8055
        volumes:
            - ./database:/database
            - ./uploads:/uploads
            - ./extensions:/extensions
        environment:
            SECRET: "replace-with-random-value"
            ADMIN_EMAIL: "admin@thewebsiteguy.uk"
            ADMIN_PASSWORD: "Stud10Adm!n"
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/database/data.db"
            WEBSOCKETS_ENABLED: "true"